# Generated by Django 5.0.7 on 2024-07-18 00:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='built_area',
            field=models.PositiveIntegerField(default=0, help_text='Built area in square feet'),
        ),
        migrations.AddField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the property was created'),
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='garage_spaces',
            field=models.PositiveIntegerField(default=0, help_text='Number of garage spaces'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Is this property featured?'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Is this property published and visible?'),
        ),
        migrations.AddField(
            model_name='property',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Lot size in acres', max_digits=10),
        ),
        migrations.AddField(
            model_name='property',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date and time when the property was last updated'),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveIntegerField(default=2024, help_text='Year the property was built'),
        ),
    ]
